# Generated by Django 4.2.7 on 2023-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_departamento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
